#!/usr/bin/env bash

cat <<"EOF"
Usage: gene cache [OPTIONS] COMMAND

Commands:
  enable               Enable local cache
  delete               Remove local cache
  get <string>         Retrive file cached
  put <key> <filename> Retrive file cached

Options:
  -h, --help           Show this message
  -p, --path=<string>  Path to send the cache ( $HOME/.gene/cache )

Run 'gene cache -h' for more information on a command.
For more details, see man gene.
EOF